Feature 2 physics and player controller script
JoyJazper/2D-Platformer-Game pull request #2
Opened 2020-06-16 07:02 UTC by JoyJazper

2020-06-16 07:04 UTC, JoyJazper commented on Assets/Script/Physics/PlayerController.cs
> +        Vector3 player_Scale;
brought them out of update to stop the script from creating the variables on every frame.

2020-06-16 22:49 UTC, JoyJazper commented on Assets/Script/Physics/PlayerController.cs
> +            //else if (player_Vertical <= 0)
Collider for Jump is not set up yet.

2020-06-17 15:15 UTC, mayankgrover requested changes

2020-06-17 15:15 UTC, mayankgrover commented on Assets/Script/Physics/PlayerController.cs
> +        Animator mainCharecter_A;
characterAnimator

2020-06-17 15:15 UTC, mayankgrover commented on Assets/Script/Physics/PlayerController.cs
> +        void Update()
atleast 4 small function

2020-06-18 13:58 UTC, merged